version: '3'

services:
  backend:
    container_name: ${COMPOSE_PROJECT_NAME}_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:3000'
  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: postgres:14.3
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data