version: '3'

services:
  backend:
    container_name: FoundationBackend
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3000'
    networks:
      - gaia
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: FoundationDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - gaia
networks:
    backend:
        name: Foundation_backend
    gaia:
        name: gaia
        external: true